version: "3.8"
services:
  dev:
    command: ./scripts/run-dev.sh
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    env_file:
      - .env
    ports:
      - 8081:8081
    volumes:
      - .:/graphql-server
  dev-linux:
    network_mode: "host"
    command: ./scripts/run-dev.sh
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    env_file:
      - .env
    ports:
      - 8081:8081
    volumes:
      - .:/graphql-server
  prod:
    build:
      context: .
      dockerfile: docker/prod.dockerfile
    ports:
      - 80:80
  docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
